### ISSUE TITLE
Improve tag UI/UX

### ISSUE THREAD

**Issue by marcoskirsch** [mro/ShaarliOS#10]
I haven't figured out how to add tags when I share a link. Is it there? The browser interface has autocomplete for tags based on existing ones. It would be cool for the app to have separate field for tags with a better UI (i.e. put the tag within an oval once it's been typed) and support for auto-complete suggestions as it's being typed.

(cool app, thanks!)

**Comment by mro** [comment]
Mi Marcos,
thank you for your suggestion, tags are set adding `#`-prefixed words at the beginning of the link description as seen e.g. on the screenshots like <img src="https://raw.githubusercontent.com/mro/ShaarliOS/master/appstore/screenshots/en-US/3_iphone35_share.png" width="80">.

So while I don't agree it's *unintuitive* (Twitter made `#` popular for such a purpose), I do agree it's *inconvenient* to fully type them. The right solution here is IMO to leverage some sort of augmented keyboard, maybe what Apple calls *[You can also provide a custom input accessory view, which is a separate view that appears above the keyboard (or your custom input view)](https://developer.apple.com/library/prerelease/ios/documentation/UserExperience/Conceptual/MobileHIG/KeyboardInputView.html#//apple_ref/doc/uid/TP40006556-CH48-SW1)*. This or similar is very likely to be part of a future release.

**Comment by mro** [comment]
Maybe *word completion* [*"You may also use UITextChecker to obtain completions for partially entered words and display the completions in a table view in a popover view."*](https://developer.apple.com/library/prerelease/ios/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/LowerLevelText-HandlingTechnologies/LowerLevelText-HandlingTechnologies.html#//apple_ref/doc/uid/TP40009542-CH15-SW47), but I want it to appear right above the keyboard, where the above screenshot shws the words `!|`, `!The` and `!But`.

**Comment by mro** [comment]
or like as an `inputAccessoryView` [this](http://stackoverflow.com/a/29661451)

**Comment by mro** [comment]
or a 3rd party [`ACEAutocompleteBar`](http://stackoverflow.com/a/35511249/349514)

**Comment by marcoskirsch** [comment]
One big tradeoff with the current tagging method, other than the question of whether it's intuitive or not, is that one cannot enter new lines in the comment field. Especially when using Markdown, this is very limiting.

At the very least or as a first step, I'd suggest putting the tags in their own input field. Don't require #, and parse out whitespace and commas.

The idea of using autocomplete right above the keyboard is cool. I was thinking something more in line with https://github.com/ali312/TLTagsControl

**Comment by mro** [comment]
switching the keyboard to the numeric one (hit `123` bottom left) gives you a `return` key (bottom right) and then you can enter newlines.

**Comment by mro** [comment]
> it more closely matches the Shaarli bookmarklet

The desktop-browser-bookmarklet isn't my design goal. 

Achieving the 90% use-cases with the least possible taps, however, is. To that end some kind of tag-completion is crucial, indeed.

**Comment by n00b12345** [comment]
I'm a little confused too. Adding #tag doesn't seem to add any tags to Shaarli. It adds them as text description. Could you help? I must be doing something wrong.

**Comment by mro** [comment]
> tags are set adding #-prefixed words **at the beginning** of the link description

@n00b12345 can you give an example of a non-working description?

**Comment by n00b12345** [comment]
@mro for some stupid reason I'd turned the tag option off in the settings. How silly of me. Terribly sorry about this. Everyone is working fine.

**Comment by mro** [comment]
@n00b12345 nevermind, I prefer false-positives over surprising showstoppers. Thank you for taking both the time to report and re-check.

**Comment by mro** [comment]
tagging UX is hard. really. https://github.com/shaarli/Shaarli/issues/594

**Comment by marcoskirsch** [comment]
FWIW Wordpress app for iOS is open source and they have a nice tag UI. Maybe it can be leveraged.
https://github.com/wordpress-mobile/WordPress-iOS

**Comment by mro** [comment]
thx for the hint. 

All I can see is a plain textbox with comma-separated tags in it, and a spinning loading indicator disappearing after ~1sec. I think I am missing something. Could you post a screenshot what you see?

**Comment by marcoskirsch** [comment]
![img_0592](https://user-images.githubusercontent.com/8085768/26854983-4c42e6e6-4ade-11e7-9093-c57367ebbf40.PNG)

Live as you type, a list of previously used tags is auto-populated and filtered.

**Comment by mro** [comment]
thx, though I don't like a dedicated, separate screens for posting+tagging.
