### ISSUE TITLE
Grab Title from in-app links

### ISSUE THREAD

**Issue by n00b12345** [mro/ShaarliOS#12]
I'm within an app, say Twitter for iOS, and I tap on a link and share it using the Shaarli extension. More often the not, the title will not be extracted from the link. This exact thing works perfectly within Safari. But not when Shaarli extension is used from other apps. 

Could there be a fix for this?

**Comment by mro** [comment]
interesting, could you give example links? Currently I don't fiddle with the title but rely on what iOS gives me by default.

**Comment by n00b12345** [comment]
@mro Try this link with the Twitter for iOS app installed. 

https://twitter.com/verge/status/732652153806979072

Now tap and hold and share the link included within that tweet. As you'll see, the title isn't extracted. This happens will all apps that isn't Safari.

**Comment by mro** [comment]
thx, I remember to have seen similar with Firefox and iCab.

**Comment by mro** [comment]
hm, just got the hint that https://github.com/mro/ShaarliOS/blob/master/ios/Share/ShareVC.m#L71 may need a bit of https://developer.apple.com/reference/uikit/uiactivityitemsource/1620455-activityviewcontroller to get the page title.

**Comment by mro** [comment]
maybe: https://gist.github.com/blork/3908619597ab4515941d

**Comment by mro** [comment]
apologies for the long delay, plz reopen if still an issue.
