### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by JanJastrow** [mro/ShaarliOS#13]
Hi,

I can't login to my fresh installation.
It just display the HTML output as an error message.
Tried HTTP and HTTPS

![img_3526](https://cloud.githubusercontent.com/assets/2591991/16948445/fdb91eae-4db4-11e6-8602-80ec33f7fe1c.PNG)
- iOS 10 b3
- iPhone 6 Plus
- ShaarliOS v1.1
- [Shaarli 0.7.0](https://github.com/shaarli/Shaarli/releases/tag/v0.7.0)
- Theme: [Shaarli-Material](https://github.com/kalvn/Shaarli-Material/releases/tag/v0.7.0)

Also, when clicking the 1Pw-Button, the App crashes immediately, but okay :smile:

**Comment by mro** [comment]
Hi Jan,
thanks for the report, that's embarassing. I have a look.

**Comment by Gehirnfussel** [comment]
Just a additional information (maybe it does matter, who knows):
My password has more then 32 characters :key: :grin:

**Comment by mro** [comment]
ok, saw it in simulator, too. So sadly the theme is too different from the original shaarli theme.

I'll hunt down how and see if the next release of shaarli *may* support https://github.com/kalvn/Shaarli-Material, too.

**Comment by mro** [comment]
1st: the template lacks the (optional) `normalize-space(string(/html/body//*[@id='shaarli_title']))`

**Comment by mro** [comment]
2nd: it doesn't have the (mandatory) logout link `normalize-space(string(/html/body//a[@href='?do=logout']/@href))` – that's IMO the only way to detect a successful login.

**Comment by mro** [comment]
can you login on the shaarli webinterface? I can't – opened https://github.com/kalvn/Shaarli-Material/issues/52

**Comment by Gehirnfussel** [comment]
Thank you. I'll try/use a different theme for now until this has been resolved by the theme.

**Comment by mro** [comment]
Now I can login and post.

Can you double-check you typed the pwd correctly? E.g. by C+P from a note where you can visually check the pwd.

**Comment by Gehirnfussel** [comment]
It's getting stranger by the minute.
I tried a different theme: didn't work
I tried the default theme with a custom css: didn't work
I tried just the default theme: didn't work

The password was c'n'pasted directly from 1Password. Pasted it to a notepad, looked good (no trailing spaces, etc).
Changed my password 8 characters (handtyped): didn't work

(Yes, login on desktop or mobile website does work without a problem.) 😕

**Comment by mro** [comment]
odd, indeed. So the login from the App always fails while it always succees from the Browser on the same device?

**Comment by Gehirnfussel** [comment]
Yes, that is correct.

**Comment by mro** [comment]
dou you think you could add a call to log uid+pwd on the server to see what goes over the wire?

**Comment by mro** [comment]
somewhere here: https://github.com/shaarli/Shaarli/blob/v0.7.0/index.php#L365 a line like

    logm('Remove me after debugging '.$login.'   '.$password);

**Comment by Gehirnfussel** [comment]
`logm($GLOBALS['config']['LOG_FILE'], $_SERVER['REMOTE_ADDR'], 'Remove me after debugging '.$login.'   '.$password);` did the trick.

It seems like the app does not even send the login.
(I don't get any calls of the login from the app; login from web does result in a log-entry.)

**Comment by mro** [comment]
ah, sorry, yes. hm.

Do you want to check against https://shaarli.dev.mro.name/material/ uid: tast pwd: t1st 
?

**Comment by mro** [comment]
hngrr. browser login fails. wait a moment.

**Comment by mro** [comment]
ok

**Comment by Gehirnfussel** [comment]
"Setup done" 👍

**Comment by mro** [comment]
interesting.

**Comment by mro** [comment]
just for fun – can you post something (safe for work)?

**Comment by Gehirnfussel** [comment]
Done.

**Comment by mro** [comment]
ok, thx. So how do we figure out the relevant difference in server configuration? Mine is https://github.com/kalvn/Shaarli-Material/issues/52#issue-166321049

What is yours?

**Comment by Gehirnfussel** [comment]
apache2 -v
Server version: Apache/2.2.22 (Ubuntu)
Server built:   Jul 24 2015 17:25:42

php -v
PHP 5.3.10-1ubuntu3.23 with Suhosin-Patch (cli) (built: May 19 2016 20:38:03)
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
    with the ionCube PHP Loader v4.6.0, Copyright (c) 2002-2014, by ionCube Ltd.

Ubuntu 14.04LTS

(Tried also with PHP 5.6.23)

---

Sorry for the confusion about the theme.

**Comment by mro** [comment]
nevermind. Can you check the effectively running php via a i.php file like http://php.net/manual/de/function.phpinfo.php#example-544

**Comment by Gehirnfussel** [comment]
[phpinfo.pdf](https://github.com/mro/ShaarliOS/files/371688/phpinfo.pdf)

**Comment by mro** [comment]
puh. a lot of stuff. Looks like php 5.6 wthich should be fine (while 5.3 wouldn't be).

Frankly I'm clueless at the moment.

**Comment by mro** [comment]
I consider running https://github.com/mro/Shaarli-API-test/blob/master/tests/test-login-ok.sh against your endpoint. You can either do so yourself (just run the script, it will ask for what it needs) or hand me your endpoint and credentials to github@mro.name

**Comment by mro** [comment]
mavbe related? https://github.com/shaarli/Shaarli/issues/595 I'll watch closely!

**Comment by mro** [comment]
maybe a trailing `/` is mandatory for paths…

**Comment by Gehirnfussel** [comment]
Oh… my… god…
It's working.
It was the trailing `/`
Would've not guessed that. 😠

Thank you!

**Comment by mro** [comment]
reopening, has to be fixed.

**Comment by mro** [comment]
@Gehirnfussel thanks for the report and your patience hunting this one down.

**Comment by Gehirnfussel** [comment]
Just to let you know: It's working fine (now) with the 'Material' Theme
