### ISSUE TITLE
Shaarli/Shaarli connection failed

### ISSUE THREAD

**Issue by konstcranky** [mro/ShaarliOS#16]
Downloaded and installed https://github.com/shaarli/Shaarli/releases/download/v0.8.0/shaarli-v0.8.0-full.tar.gz

When trying to connect - receiving:

Connection failed.
Required login form field slot missing.

BTW, im using self-signed ssl certificate.

**Comment by mro** [comment]
thx for the report, will have a look within 8h.

**Comment by mro** [comment]
Hi @konstcranky 

can you try against https://shaarli.dev.mro.name/v0.8.0/ – a clean install from the url above. Works for me with the ShaarliOS App-Store version v1.1.

Does the webinterface of your shaarli work? i assume you use the shaarli out of the box without a changed theme.

Can you verify?

Maybe the self-signed cert causes the issue, but in this case I would expect a different message. If you email me (temporarily valid) login credentials, I can have a closer look. See https://github.com/mro/ShaarliOS#bug-reports for the email address.

**Comment by konstcranky** [comment]
Thank you. I will check tomorrow

**Comment by konstcranky** [comment]
Thank you again. My problem was in self-signed cert.

Tip#2 from https://blog.httpwatch.com/2013/12/12/five-tips-for-using-self-signed-ssl-certificates-with-ios/ helped me.

**Comment by mro** [comment]
thank you for reprting, now we know how to deal with self-signed certs.
