### ISSUE TITLE
Support for Shaarli's 0.9.x REST API

### ISSUE THREAD

**Issue by lx-s** [mro/ShaarliOS#17]
Hey!

Shaarli will receive a REST API in the near future (#https://github.com/shaarli/Shaarli/issues/609).
I think supporting this could greatly enhance ShaarliOS (from a feature and robustness standpoint),
and could simplify your code (no more parsing HTML?).

Do you have plans (or the time) to work on this?

**Comment by mro** [comment]
yes, I do, as soon as there are tests that ensure compliance of new installations as well as demonstrate usage.

Closing for now, but shall re-open.
