### ISSUE TITLE
Update Shaarli links to the community fork

### ISSUE THREAD

**Issue by dimtion** [mro/ShaarliOS#2]
It seems that most links to the Shaarli project are going to : http://sebsauvage.net/wiki/doku.php?id=php:shaarli
True, it is the original project and credit must be given to Sebsauvage, but It would be easier if every user is using a more up to date Shaarli. Why not using the [community fork](https://github.com/shaarli/Shaarli) ?

**Comment by mro** [comment]
I want to stay compatible with the original as long as possible on the one side.

On the other you are right and I will re-think about linking to the community fork more prominently.

But mostly it's for compatibility and testing reasons. But if I have a compatibility testing script, I may link to the more 'dynamic' community fork. Or even better add the test to the community shaarli itself - if accepted.

How do you ensure compatibility of your app with current master of the community fork?

**Comment by mro** [comment]
poke. See also https://github.com/shaarli/Shaarli/issues/16#issuecomment-137886509

**Comment by dimtion** [comment]
I have for the moment created no automated tests to ensure compatibility with shaarli/Shaarli:main. It's a shame, but I was not lazy enough to make them. So for the moment, when a new version of Shaarli is release I try it "by hand" and edit the app accordingly. It is enough today because of the little number of functionalities (only post a link) and the slow rate of Shaarli updates. 
I am aware that this process is suboptimal and very error prone. But it was good enough given the relative size of the project.

Ultimately I second you on https://github.com/shaarli/Shaarli/issues/342, if Shaarli was built with a third-party-friendly API, creating an automated test suite for our apps would be a peace of cake.

**Comment by mro** [comment]
ic, so you may be interested in what I'm doing at [test-post.sh](https://github.com/mro/Shaarli-API-test/blob/master/scripts/test-post.sh) - that's the flow I use to add/post a link.

There's a strange issue I could need help with - I don't understand why the [Atom Feed brings strange results after adding a link](https://travis-ci.org/mro/Shaarli-API-test/jobs/78946288#L363) for some php/shaarli version combinations.

I'd very much appreciate if you could you have a look

1. if the flow in `test-post.sh` is what your app uses
2. you can help me understand why adding the link doesn't fully work (at least in terms of the atom feed)

**Comment by mro** [comment]
now as the [tests](https://github.com/mro/Shaarli-API-test#shaarli-api-test) I will wait until Shaarli stabilizes a bit (until the next Shaarli release or so) and then adjust the links & text.
