### ISSUE TITLE
Doesn’t work on iOS 11.3

### ISSUE THREAD

**Issue by lilarcor** [mro/ShaarliOS#21]
Hello, it can’t logon with ios11.3, I got some html source code , seems it’s the main page of shaarli, but app never net let me in. It’s about two years since last release, will you release a new version?

**Comment by mro** [comment]
Hi,

thank you for the report, yes, there will be a new version soon.

However, it does work on iOS 11. Can you check if the html goo message is false alarm.

And what precise shaarli version do you run?

**Comment by lilarcor** [comment]
Thanks for your quick reply. I am running 1.1 ,downloaded from IOS App Store. ![Image](https://i.imgur.com/1gpftyX.jpg)

FYI

**Comment by chrisbeckstrom** [comment]
Any idea what's causing this? I'm running Shaari iOS v1.1+9v428a6 on iOS 12.0 (16A366) and getting basically the same issue @lilarcor is getting. I initially downloaded v0.10.2 on my server.

I've also tried:

- using the latest Shaari release from the releases page  
- cloning the git and compiling
- trying out a few different releases from the releases page  
- trying on a different server
- reinstalling the iOS app
- I can't find any errors in my apache log, nor in the `log.txt` file in the Shaarli directory  
- various combinations of permissions, my apache user (`www-data`) owning the Shaarli directory, doing `chmod -R 777` on the Sharrli directory, etc.

About my setup:  

- I have an `.htaccess` file at the root of my server web directory which does some things, mostly for running wordpress stuff  
- OS: Linux Debian 8.7  
- 

Strangely, **I can use the iOS app to connect to the demo instance successfully**, and I can share links to it. For the life of me I can't figure out why it's not working with my own server. I suspect I'm missing some detail, but don't know what it is.

I **really really** want to get this working, as I absolutely love this! Working toward the whole indieweb thing, and using Pocket to track what I'm reading is one of my last steps to self-hosted independence. Thanks for all your hard work and in advance for any suggestions you might have!

**Comment by mro** [comment]
I'll look into it, it may take until sunday, however.

**Comment by mro** [comment]
can you install the shaarli you use (in case of failure an untampered with https://github.com/shaarli/Shaarli/releases/tag/v0.10.2) on a different webserver or subdirectory without any possibly interfering `.htaccess`?

I suspect there's some HTTP stuff (auth?) going on.

**Comment by lilarcor** [comment]
@mro I think the problem has been fixed after I tried the new version v0.10.2. Thanks for helping. And I found another bug. I will post a new ticket.
