### ISSUE TITLE
IOS client makes random tiltle

### ISSUE THREAD

**Issue by lilarcor** [mro/ShaarliOS#23]
I am an IOS user with latest version. Server is running v0.10.2. I found if I leave the title empty when shaarli a new url in IOS client, the server side will auto make a random title for it, which starts with ? (eg ?cOovxw).
I think it makes sense. But if I'm a new IOS user, I could be confused. I  think the title should take some beginning wording of the content if user leaves it empty. That will be much reasonable.

**Comment by mro** [comment]
apologies for the long delay, plz reopen if still an issue.
