### ISSUE TITLE
Fail to connect to alternative HTTP port

### ISSUE THREAD

**Issue by raycheung** [mro/ShaarliOS#28]
I self-hosted Shaarli server on an alternative HTTP port, but the app seemingly doesn't recognize <host>:<port> pattern in the URL field.

How should I make it work please?

**Comment by raycheung** [comment]
Ah no... perhaps it's a password issue, which I used a password that contains `#` or `$`.

**Comment by mro** [comment]
@raycheung thank you for your report, can you please enter the backend URL https://demo.0x4c.de:8443/shaarli-v0.11.1/ (without `https://`) with uid `demo` and pwd `demodemodemo` in settings and then

* ensure you have the app version 1.2.2 (most recent),
* post a note from within the app,
* post a url via share sheet from e.g. Safari,
* tell me about it here immediately after.

Thanks!

**Comment by mro** [comment]
P.S.: on Monday I will prepare a demo backend with said characters in the pwd.

**Comment by mro** [comment]
I shall prepare and submit to Apple tomorrow.

**Comment by mro** [comment]
@raycheung can you confirm the issue is fixed in 1.2.3 https://github.com/mro/ShaarliOS/milestone/8?

P.S.: I'd be happy if you [rate the App](https://apps.apple.com/de/app/shaarlios/id1027441388?mt=8&action=write-review).

**Comment by raycheung** [comment]
@mro Strangely it doesn't seem to work. I fail to connect to my server on alternative HTTP port now, yet in the previous release I could -- with a good simple password that contained no special character.

**Comment by raycheung** [comment]
It blanks for a second, then prompts 'The request timed out.'

Note my server on that alternative HTTP port is hosted w/o https, as I used the host internally behind VPN.

**Comment by raycheung** [comment]
To clear the confusions, the latest version is confirmed to work!

**Comment by mro** [comment]
finally, thank you for your patience!
