### ISSUE TITLE
“linkform not found”

### ISSUE THREAD

**Issue by johannesmirus** [mro/ShaarliOS#29]
I get the above mentioned error when trying to (re)connect to my self-hosted Shaarli. Presumably since the last app update. 

![849A8E8D-F530-4376-A8FA-01529FD3C511](https://user-images.githubusercontent.com/15308906/78460650-df481e80-76c2-11ea-962b-0dee942c92d3.jpeg)

Thanks for taking a look onto it and for your fantastic work!

**Comment by mro** [comment]
@johannesmirus thank you for your report, what precise shaarli version is you server running?

And can you please enter the backend URL https://demo.0x4c.de/shaarli-v0.11.1/ (without https://) with uid demo and pwd demodemodemo in settings and then

* ensure you have the app version 1.2.2 (most recent),
* post a note from within the app,
* post a url via share sheet from e.g. Safari,
* tell me about it here immediately after.

Thanks!

**Comment by johannesmirus** [comment]
Did it and it worked with your demo installation.

You are running v0.11.1 though, I have the latest stable release v0.10.4 running. Could that cause a problem?

**Comment by mro** [comment]
@johannesmirus IMO the fix is in c6f6748, I shall prepare and submit to Apple tomorrow.

Thanks for you patience and your help!

**Comment by johannesmirus** [comment]
Perfect! Thanks for your fast und helpful answers! Im looking forward to the next release.

**Comment by mro** [comment]
@johannesmirus can you confirm the issue is fixed in https://github.com/mro/ShaarliOS/milestone/8?

P.S.: I'd be happy if you [rate the App](https://apps.apple.com/de/app/shaarlios/id1027441388?mt=8&action=write-review).

**Comment by johannesmirus** [comment]
Sorry, still the same error. :(

**Comment by mro** [comment]
sure you have the v1.2.3?

**Comment by mro** [comment]
works https://demo.0x4c.de/shaarli-v0.10.4/ – what could possibly be a relevant difference?

**Comment by johannesmirus** [comment]
Sorry, works neither with my installation nor with your demo v0.10.4 installation. However, the error message moved from the setup form to a message when trying to post

![IMG_4676](https://user-images.githubusercontent.com/15308906/78543267-b6c24080-77f8-11ea-840b-9266371a7ce5.jpg)

**Comment by mro** [comment]
got it!

**Comment by mro** [comment]
@johannesmirus can you please give the v1.2.4 a try, the v1.2.3 was a shame :-(.

**Comment by johannesmirus** [comment]
YES! It worked with your demo installation, with my own installation, via sharing from Safari. Thank you very much for all your efforts! I'm very happy with your quick and friendly support.

**Comment by mro** [comment]
Thanks for you patience and your help!
