### ISSUE TITLE
1.2.5 requires https 

### ISSUE THREAD

**Issue by ParoTheParrot** [mro/ShaarliOS#38]
Why? I don't have https so i can't use shaarlios .
the old app was good enough ! A revamp isn't necessary!

**Comment by mro** [comment]
Thanks for the report, can you elaborate why you now need https? Do you have an error message for me, a screenshot? How was the situation with v1.2.4?

**Comment by mro** [comment]
is this what you see?
![2020-04-14-161813-IMG_2785_--_ios_shot_shaarli](https://user-images.githubusercontent.com/61800/79235470-ef52c180-7e6b-11ea-9057-5526ebae6bde.PNG)

**Comment by mro** [comment]
#20
