### ISSUE TITLE
App is not able to log in tomorrow shaarli

### ISSUE THREAD

**Issue by rcrath** [mro/ShaarliOS#41]
iOS 13.3.1, Shaarli 0.11.1

Cannot login in settings for plugin. Triple checked credentials. 

![1E3595B5-4828-4771-B4AC-C89491DC7A0C](https://user-images.githubusercontent.com/944636/79678433-4374e300-8197-11ea-8421-64d0617cccc4.png)

Related to issue [#125] ?

**Comment by mro** [comment]
thanks for the report, I think I see the bug.

As a workaround: please try without the 'http://' in the beginning.

**Comment by mro** [comment]
@rcrath did the suggested workaround mitigate your problem?

**Comment by rcrath** [comment]
Yes. Fixed it

**Comment by mro** [comment]
@rcrath I'd be happy if you could rate the app https://apps.apple.com/it/app/shaarlios/id1027441388?mt=8&action=write-review
