### ISSUE TITLE
Host with sub domain not found

### ISSUE THREAD

**Issue by lbrack1** [mro/ShaarliOS#42]
The domain https://bookmarks.leobrack.co.uk points to the shaarli directory on my server and this works from the browser.

When connecting from the app I am getting the hostname cannot be found.

![62D94328-BFA4-4180-B0B9-B42A5CF9CD11](https://user-images.githubusercontent.com/29924655/79906132-306c4800-840f-11ea-8d11-8d15eafa6133.png)

![B2CD48EC-B7E4-4E74-9B54-EFC7ADF21F55](https://user-images.githubusercontent.com/29924655/79906342-8a6d0d80-840f-11ea-84a9-8196f33238f0.png)

**Comment by lbrack1** [comment]
Ah, https:// vs www

**Comment by mro** [comment]
Thanks for the report, it's a real bug, the same issue as #41
