### ISSUE TITLE
Try out https://github.com/ArthurHoaro effort

### ISSUE THREAD

**Issue by mro** [mro/ShaarliOS#47]
https://github.com/shaarli/Shaarli/pull/1511#issuecomment-683431179

**Comment by mro** [comment]
Yikes! https://github.com/shaarli/Shaarli/pull/1534

**Comment by mro** [comment]
Try out
https://shaarli-next.hoa.ro/?post=https://github.com/mro/ShaarliOS/issues/47
https://shaarli-next.hoa.ro/?do=configure

**Comment by mro** [comment]
not quite there yet.  The configure is perfect, the `?post` makes  📱 ShaarliOS think the service-endpoint is https://shaarli-next.hoa.ro/login. I have to nail it down why.

**Comment by mro** [comment]
the loginform returns with the linkform and action. Need to honour that. Previously just posted the linkform to the endpoint.

Will take a bit to change that.

**Comment by ArthurHoaro** [comment]
I'm not sure to understand what's your issue is. Let me know if there is something I can do on my end.

**Comment by mro** [comment]
I see, issue not that I ignore the form action (being identical to the form document url), but that I ignore the form base url and stubbornly post to the service endpoint. Have to change that and post to the form's html document's base url.
