### ISSUE TITLE
Can’t login

### ISSUE THREAD

**Issue by smonff** [mro/ShaarliOS#59]
Hi,

Trying to use SharliOS, but can’t login to my instance. The address is [balik.network/linx](https://balik.network/linx).

I tried all sort of combinations, like using HTTP or adding the protocol explicitly. I also tried to change my password.

Maybe the domain name is suspicious since it contains `net`, maybe SharliOS misinterpret it.

The only message I have is `wrong login/password` but I am sure my credentials are right since I currently use them on other clients.

Help would be appreciated. Thanks.

**Comment by mro** [comment]
uh, just seen the issue now. Will have a close look in the next 48h.

**Comment by mro** [comment]
@smonff thanks for reporting,

1. does browser login with the same credentials work?
2. also on the mobile device?
3. can you add a ShaarliOS screenshot of the failure here?
4. what does the server log say?
5. can you clone the shaarli under the same hostname with new path and credentials and disclose them credentials to me? E.g. via https://paste.mro.name/

**Comment by smonff** [comment]
Hi,

thanx for the answer.

- 1 and 2 : everything is fine, I sure checked that before reporting
- see the screenshot below
- 4 and 5 : I’ll get back to you for this, afaik, nothing special in the logs

![F7342A61-C4C4-41AB-8BE7-275C734BBBA6](https://user-images.githubusercontent.com/1219097/124734260-3ca9cb80-df15-11eb-9f9b-143579fa6035.png)

**Comment by smonff** [comment]
Since it doesn’t seem to be a password issue, it could be related to something linked to the `.network` domain name or maybe the `/linx` extra path to Shaarli. I am gonna setup a subdomain and see if it helps.

**Comment by mro** [comment]
a clone under e.g. /liny would be great.

Can you meanwhile test against the instance at https://demo.mro.name/shaarli-v0.11.1/ with 

user demo
pwd demodemodemo

to rule out issues on the phone & network side.

**Comment by mro** [comment]
or also the official https://demo.shaarli.org/

**Comment by smonff** [comment]
I confirm I can login from the demo instance.

**Comment by smonff** [comment]
I can also connect to the second one.

**Comment by smonff** [comment]
So ok, I did a thing and it solved the problem. It was a password paste problem. 

I changed my password by removing all “special” characters and became able to login to my instance. I mean the new password only use [a-z][0-9] chars and their capital equivalent.

Old password was something like `:8-$;(B%Z_rM]]?i?p{'+]1|xQk008]$,L}\z2HxTB^%YpEl`. Maybe some escape sequence or something created an issue.

**Comment by mro** [comment]
is that a leading blank prior the `:`

**Comment by mro** [comment]
nice password though, will check.

**Comment by smonff** [comment]
> is that a leading blank prior the `:`

No leading blank: only Github’s formatting style can be incriminated.

**Comment by smonff** [comment]
It fixed my initial issue and you seem to have find a related improvement, so I close it.

**Comment by mro** [comment]
@smonff thanks for reporting and you patience!

The fix is available in code and will be submitted to the App Store tomorrow. Then there will also be new promo codes at #58

Thanks for using #shaarlio💫 and [please rate ⭐️ the app 📱](https://apps.apple.com/it/app/shaarlios/id1027441388?mt=8&action=write-review), be it good or bad.

**Comment by smonff** [comment]
@mro I am happy if it helped to improve your app and make other people life easier by avoiding bugs.
