### ISSUE TITLE
https not working

### ISSUE THREAD

**Issue by chazdiezal** [mro/ShaarliOS#6]
I can connect with http without any issues but when I try with https enabled the new note doesn't save.

**Comment by mro** [comment]
thanks for your report, It's a bit scarce, can you give me some details, most important about the SSL certificate? If you prefer via [private email](mailto:shaarlios@mro.name?subject=https://github.com/mro/ShaarliOS/issues/6).

**Comment by mro** [comment]
maybe similar https://github.com/shaarli/Shaarli/issues/356

If no additional information comes in, I will have to close this issue.

**Comment by mro** [comment]
ping @chazdiezal ?

**Comment by mro** [comment]
@chazdiezal sorry, your reply slipped through. Can you [email](mailto:shaarlios@mro.name?subject=[ShaarliOS]%20Bugreport&body=Thank%20you%20very%20much%20for%20your%20bug%20report.%20I%20am%20very%20sorry%20for%20the%20inconvenience.%0D%0A%0D%0ATo%20be%20able%20to%20quickly%20hunt%20down%20and%20eliminate%20the%20bug,%20please%20include%20some%20additional%20information:%0D%0A%0D%0A-%20can%20you%20attach%20a%20screenshot%20of%20the%20bug%20and%20the%20last%20visible%20screen%20prior%20the%20bug%20(will%20be%20treated%20confidential)?%0D%0A-%20what%20is%20the%20Shaarli%20version%20you%20use%20(preferably%20the%20download%20URL%20you%20got%20it%20from)?%0D%0A-%20which%20template%20are%20you%20using%20(if%20other%20than%20the%20default,%20also%20preferably%20the%20download%20URL)?%0D%0A-%20are%20you%20using%20https,%20if%20so:%20who%20issued%20your%20certificate?%0D%0A-%20can%20you%20attach%20device%20logs%20or%20crash%20reports?%0D%0A%0D%0AThank%20you%20very%20much,%0D%0A%20%20%20%20Marcus%20Rohrmoser) me the results of a https://www.ssllabs.com/ssltest/analyze.html scan?

**Comment by chazdiezal** [comment]
@mro, ssl labs server report has been sent to you via email as well
[SSL Server Test_ allthingssquared.pdf](https://github.com/mro/ShaarliOS/files/70773/SSL.Server.Test_.allthingssquared.pdf)
, thanks!

**Comment by mro** [comment]
Hi @chazdiezal ,

can you send me a screenshot of the complete settings screen prior and after hitting the „Done“ button top right?

I want to know both how the fields are filled in and what the error messae says.

The „URL“ has to be without protocol: www.allthingssquared.com/shaarli/
and the ‚https‘ switch has to be on (I will rework this in the next release)):

Thank you for your patience!

**Comment by chazdiezal** [comment]
Thanks for looking into this.

![img_0440](https://cloud.githubusercontent.com/assets/11147538/11978258/f5e11600-a981-11e5-818d-18179dfe9aaa.PNG)
![img_0441](https://cloud.githubusercontent.com/assets/11147538/11978259/f5edd854-a981-11e5-9c66-8f52f8491d63.PNG)

**Comment by chazdiezal** [comment]
Just to make note...in the 2nd screenshot when I hit "shaare" after filling in the info I want to save nothing occurs.  No error message, I check my shaarli and note doesn't get saved, nothing.  I then have to hit cancel, switch off https, then save the note over http....hope this helps.

**Comment by mro** [comment]
ok, helps. Further investigation may take a few days.

**Comment by mro** [comment]
IMO fixed in v1.1 9b428a6
