### ISSUE TITLE
not working fully on Chrome under iOS 15.2.1 on an iPhone 12 mini

### ISSUE THREAD

**Issue by sounds2k** [mro/ShaarliOS#61]
Hi,

this extension doesn't appear to be working properly for me on my iPhone 12 mini running iOS v15.2.1, there appear to be two issues.

Firstly - if I use Google Chrome, the page title is blank - and you can't enter one. The summary is also empty (other than the default tags). If I use safari, the page title and summary (where possible) is pre-populated. It does grab an image if available.

Secondly - if the link contains certain characters, for example:

https://www.westlands.org.uk/page/?title=Term+Dates+21%2F22&pid=92

the link which gets added to Shaarli is of the format:

https://shaarli.sounds.qc.to/shaare/h816Hg

which doesn't work if you click on it. Other pages (e.g., https://github.com/mro/ShaarliOS) work fine.

App version is v1.4.2+8108981, Shaarli server version is listed in the "Server administration" page as "dev", although docker is configured to use "shaarli/shaarli:latest". It does say on that page it's running "Running PHP 7.4.27", which has changed from when it was initially installed and set to use the image "shaarli/shaarli:master".

A screenshot (from Chrome) taken at the main github page (https://github.com/mro/ShaarliOS) is attached.

![IMG_2755](https://user-images.githubusercontent.com/65366965/151663041-e799bf0d-6ab8-457c-b603-7416775770cf.jpeg)
.

**Comment by mro** [comment]
thanks for reporting, I shall look into it!

**Comment by mro** [comment]
first – https://github.com/mro/ShaarliOS/issues/56 won't change soon.

second - I suspect the westlands interfere with the scraping javascript https://github.com/mro/ShaarliOS/issues/57 and that needs some attention. Stay tuned.

**Comment by mro** [comment]
am puzzling how I could test the js execution of https://github.com/mro/ShaarliOS/blob/master/swift4/Share/Scraper.js against https://www.westlands.org.uk/page/?title=Term+Dates+21%2F22&pid=92

**Comment by mro** [comment]
the plus '+' indeed triggers the issue. Haven't nailed it yet, however.

**Comment by mro** [comment]
now the chrome issue – I know the same from Firefox and iCabMobile. It just doesn't share the URL ass URL but URL + Title + Text mangled together as Text. Which I don't register for (so far). https://github.com/mro/ShaarliOS/issues/12
