### ISSUE TITLE
Can not share via share menu

### ISSUE THREAD

**Issue by jaschaurbach** [mro/ShaarliOS#64]
I just bought the app and it works fine except hen I try to share a website to #shaarliOS, I do not get the option to do so.
My share menu looks like this one (iOS 16.2). This is the reason why I bought the app - to simply share something into any bookmarks.

![IMG_3283](https://user-images.githubusercontent.com/2017105/209883754-43e997db-e6b0-43e8-8eb4-a67e8c9561f4.PNG)
![IMG_3284](https://user-images.githubusercontent.com/2017105/209883771-8160cc88-dd03-4f96-b48a-b5b9cced337a.PNG)

Do I need to do some settings somewhere? O does the App need an update?

**Comment by mro** [comment]
thanks for the report, I'll hunt for a screenshot how to activate the share extension and post it here.

**Comment by jaschaurbach** [comment]
Do not know why but it works on a new phone 🤷‍♂️

**Comment by mro** [comment]
may it interfere with other extensions / filters / ad blockers?
