### ISSUE TITLE
Logging in with bad credentials displays HTML code as error message

### ISSUE THREAD

**Issue by joedemo42** [mro/ShaarliOS#7]
Well, the title says it all.
When you try to login to an otherwise valid server using bad credentials, you get a `<script>alert("Wrong login/password.");document.location='?do=login';</script>` as the error message.

This is probably not intended. Happend to me with the AppStore version and shaarli/Shaarli@92ba7b573f2833bd35c7eb2fc7fdbeb1a0ac7b44

**Comment by mro** [comment]
filtering the error responses out of the html/javascript rsponses is a bit tedious and shaky. I will add a test to https://github.com/mro/Shaarli-API-test to properly tst it against a range of shaarli versions.

**Comment by mro** [comment]
fixed in v1.1 9b428a6
